version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: local-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db # 데이터를 로컬에 영구 저장하기 위한 볼륨 마운트

volumes:
  mongo-data: